apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  # Total storage for this PV is 1GB - the Pods can "claim" how much storage they need later.
  capacity:
    storage: 1Gi
  # https://www.computerweekly.com/feature/Storage-pros-and-cons-Block-vs-file-vs-object-storage
  volumeMode: Filesystem
  storageClassName: standard # `kubectl get sc` - a config for PV provisioning 
  accessModes:
    - ReadWriteOnce # Only claimed by a single Node
    # - ReadOnlyMany  # Read only by multiple Nodes
    # - ReadWriteMany # Read Write by multiple Nodes

  # Since minikube is only a dummy Node running in a VM environment, this PV can only be claimed once because the path is bound to this Node. Thus, ReadWriteOnce is the only choice here.
  hostPath:
    path: /data
    type: DirectoryOrCreate
---
# Host Node claiming this PV - Provider to Pods
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  # Claim the PV by name
  volumeName: host-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  # Requesting max storage
  resources:
    requests:
      storage: 1Gi