# Deploying auth API

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  # Containers
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: aixufey/kub-networking-auth:latest