apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
      # dockerfile listening on port 80
    - protocol: "TCP"
      port: 80   
      targetPort: 80
