apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  # Containers
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: task
          image: aixufey/kub-networking-tasks:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks