# Deploying users API

apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  # Containers
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: aixufey/kub-networking-users:latest
          env:
            - name: AUTH_ADDRESS
              # value: localhost  # Communication to auth container IF within the same Pod!
              value: "10.99.145.1"  # Since auth is in a different Pod, we assigned IP from ClusterIP by k8s.