# Deploying users API

apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  # Containers
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: aixufey/kub-networking-users:latest

        - name: auth
          image: aixufey/kub-networking-auth:latest