version: "3.8"

services:
    # https://hub.docker.com/_/nginx/
    server:
        image: "nginx:stable-alpine"
        ports:
            - "8000:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    php:
        # Build this interpreter and bind the volume to host so we can work on the code.
        build:
            context: ./docker
            dockerfile: php.dockerfile
            volumes:
                - ./src:/var/www/html:delegated # Batching to improve performance as we don't need to sync the files.

            # https://github.com/docker-library/php/blob/50c8b1ceaefdaebc4df51322f1e0dc149a1cda15/8.3-rc/alpine3.19/fpm/Dockerfile
            # This image exposes port 9000, and we can map nginx to it inside nginx.conf.
    mysql:
        image: mysql:5.7
        env_file:
            - ./env/mysql.env
    composer:
        build:
            context: ./docker
            dockerfile: composer.dockerfile
        # Reflecting the volume from composer container to host. When app is installed in container, we will get the app in src folder in host.
        volumes:
            - ./src:/var/www/html
    # artisan:
    # npm:
