# https://docs.docker.com/compose/compose-file/compose-versioning/
# Docker engine 20 uses compose file version 3.8
version: "3.8"
services:
    mongodb:
        image: "mongo"
        volumes:
            - data:/data/db
        # environment:
        #     # Object use "- K:V" pair, single value use "="
        #     # MONGO_INITDB_ROOT_USERNAME: sparrow
        #     # MONGO_INITDB_ROOT_PASSWORD: 123123
        #     - MONGO_INITDB_ROOT_USERNAME=sparrow
        #     - MONGO_INITDB_ROOT_PASSWORD=123123

        # Using env file
        env_file:
            - ./env/mongo.env
        container_name: mongodb

        # networks: Docker Compose automatically creates a network for all containers in a compose file
        # goals-net, we can use other network as well
    backend:

    #frontend:

# Named volumes, if using same name then container will share the same volume
# https://docs.docker.com/get-started/08_using_compose/#use-docker-compose
volumes:
    data: 
